### ISSUE TITLE
"Fixture 'config' not found"

### ISSUE THREAD

**Issue by LeeShuaiyu** [xiaolong-snnu/PENN#1]
When running 'train.py', the following error occurred while 'test.py' runs well. Would you please tell me how can I solve this problem?
![image](https://user-images.githubusercontent.com/108048938/236977214-373cf03e-0f8f-48f3-83db-fbd37a3c02d3.png)

**Comment by xiaolong-snnu** [comment]
Hi LeeShuaiyu,

I found a solution here https://blog.csdn.net/weixin_44017891/article/details/103418031.

It said you should rename the function test() in train.py since the name 'test' is reserved by PyCharm. If we name a function like test_xxx(), something goes wrong.

**Comment by LeeShuaiyu** [comment]
I truly appreciate your help, This issue seems to be resolved well. Wish you a wonderful day ahead.
